### ISSUE TITLE
docformatter removed but only in CI?

### ISSUE THREAD

**Issue by thegcat** [pretix/pretix-plugin-cookiecutter#12]
bbed3b6c225f11374cb69d15ed98aca29ecf77e2 removes `docformatter` from the CI configs, but it is still in the git commit hook, the dev install instructions and even in the `pip install` line in the `gitlab-ci.yml`. Are these oversights or is it expected that `docformatter` runs locally but not on the CI?

**Comment by thegcat** [comment]
(I'll be happy to make a pull request should those be oversights)

**Comment by raphaelm** [comment]
Yeah, it's an oversight, thanks for watching out! I had just removed it from many CI files from our plugins because it was really annoying, but I missed we have it in other places as well.

(For future reference, I removed docformatter, since it's doing nothing in most plugins except being annoying when it disagrees with black or isort about where to put whitespace)
