### ISSUE TITLE
Tests > Run "py.test tests" fails on GitHub

### ISSUE THREAD

**Issue by gabriele-h** [pretix/pretix-plugin-cookiecutter#8]
Disclaimer: I am not familiar with cookiecutters and only very, very vaguely with CI/CD.

I tried using the pretix-plugin-cookiecutter and pushed it to a private repository. I made a minor change (added urlpatterns to urls.py) and `py.test tests` fails, with this being the last call:
```
File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/pretix/base/secrets.py", line 7, in <module>
    from cryptography.hazmat.primitives.serialization.base import (
ImportError: cannot import name 'Encoding' from 'cryptography.hazmat.primitives.serialization.base' (/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py)
```
This does not seem to be related to the change I made.

**Comment by raphaelm** [comment]
This is not related to the cookiecutter or your plugin, but to pretix, which currently is incompatible with the latest version of ``cryptography``. We'll hopefully release pretix 3.16 today, which will fix this. Otherwise you'd manually need to add ``cryptography==3.3.*`` to the ``pip install`` line of the CI until 3.16 is released.
